version: "3"
services:
  caddy:
    build: docker/caddy
    depends_on:
      - php_fpm
    volumes:
      - .:/var/app
    ports:
      - "8080:8080"
  php_fpm:
    build: docker/php_fpm
    image: example_php_fpm
    volumes:
      - .:/var/app
  php_fpm_debug:
    build: docker/php_fpm_debug
    depends_on:
      - php_fpm
    volumes:
      - .:/var/app

